config/routes.rb
Rails.application.routes.draw do

  resources :articles, :upload_images, :categories#, :products
  root 'products#new'
  resources :products do
  	collection do
  		post 'temp_image_update' => 'products#temp_image_update', as: 'temp_image_update'
  	end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	# belongs_to :product
	has_many :product_categories, :dependent => :destroy
	has_many :products, :through => :product_categories

	validates_uniqueness_of :name, message: "Category name already taken!"
	validates_presence_of :name, message: "Please enter category name"
	before_destroy :check_products_present

	def check_products_present
		if !(self.products.present?)
			errors.add(:name, 'error')
			return false
		end
	end

	def check_products
		if self.products.present?
			return false
		else
			return true
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	has_many :upload_images, :dependent => :destroy
	has_many :product_categories, :dependent => :destroy
	has_many :categories, :through => :product_categories

	accepts_nested_attributes_for :upload_images, allow_destroy: true, reject_if: :all_blank
	accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: :all_blank
	validates_presence_of :name,  :message => "Please enter name"
	validates_presence_of :name, :on => :update, :message => "Please enter name"
	# validate :check_category
	# validate :image_presence

	def image_presence
		if self.upload_images.present?
			return true
		else
			errors.add(:name, "Please select image") if !(self.upload_images.present?)
		end
	end

	# def check_category
	# 	binding.pry
	# end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	belongs_to :product
	belongs_to :category

	# def self.check_present(obj)
	# 	binding.pry
	# 	if !(obj.present?)
	# 		errors.add(:name,"Can't Be Blank ")
	# 	end
	# end
end

app/models/temporary_image.rb
class TemporaryImage < ActiveRecord::Base
end

app/models/upload_image.rb
class UploadImage < ActiveRecord::Base
	# has_attached_file :image, :styles => { :small => "150x150>" }
	belongs_to :product
  has_attached_file :image, {:styles => {:large => "640x640>",
                                         :small => "200x200>", 
                                         :thumb => "60x60>"}}#.merge(UPLOAD_IMAGE_PATH)

	validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 2.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
	validates_presence_of :image,  :message => "Please enter Image"
	validate :image_validation#, :if => "image?"  
	# before_validation :check_image
  def image_validation
    errors.add(:image, "size can't less than 5 MB") if self.image.size < 5000
  end
  def self.check_image(product)
  	binding.pry
  	errors.add(:image, "size can't less than 5 MB")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		
	end

	def new
		
	end

	def create
		
	end
	def edit
		
	end
	def update
		
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :find_category, only:[:edit, :update, :destroy]

	def index
		@categories = Category.all.order('created_at DESC')
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path, :notice => 'Category successfully saved!'
		else
			render 'new'
		end
	end

	def update
		if @category.update(category_params)
			redirect_to categories_path, :notice => 'Category successfully updated!'
		else
			render 'edit'
		end
	end

	def destroy
	 	if @category.destroy
		else
			flash[:message] = 'Category have products, not deleted'
		end
		redirect_to categories_path
	end

	private

	def find_category
		@category = Category.find(params[:id])
	end

	def category_params
    params.require(:category).permit!
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :find_product, only:[:edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		category_ids = params[:product][:product_categories][:category_id].reject(&:blank?)
		if category_ids.present?
			if @product.save
				product_categories_create
				redirect_to products_path, :notice => 'Product successfully saved!'
			else
				render 'new'	
			end
		else
			flash[:message] = "please select category"
			render 'new'
		end
	end

	def update
		category_ids = params[:product][:product_categories][:category_id].reject(&:blank?)
		if category_ids.present?
			if @product.update(product_params)
				ProductCategory.where(product_id: @product.id).destroy_all
				product_categories_create
				redirect_to products_path, :notice => 'Product successfully updated!'
			else
				render "new", :locals => { :template => @product.id }	
			end
		else
			flash[:message] = "please select category"
			render "new", :locals => { :template => @product.id }
		end
	end

	def destroy
		@product.destroy
		redirect_to products_path
	end

	def temp_image_update
		@temp_image = TemporaryImage.new(image: params[:media_file])
	end

	private

	def product_categories_create
		category_ids = params[:product][:product_categories][:category_id].reject(&:blank?)
		category_ids.each do |id|
			ProductCategory.create(product_id: @product.id, category_id: id)
		end	
	end

	def find_product
		@product = Product.find(params[:id])
	end

	def product_params
    params.require(:product).permit(:name, :categories_attributes => [:id, :name])
  end
end

app/controllers/upload_images_controller.rb
class UploadImagesController < ApplicationController

	def index
		@images = UploadImage.all
	end

	def new
		@image = UploadImage.new
	end

	def create
		if upload_image_params[:image].present?
			upload_image_params[:image].each do |image|
				UploadImage.create(image: image)
			end
			redirect_to upload_images_path
		else
			render 'new'
		end
	end

	private

	 def upload_image_params
    params.require(:upload_image).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 	def link_to_add_image_fields(name, f, association, disp, partial = "upload_image_fields", locals = {})
    new_object = association.to_s.classify.constantize.new
    	partial ||= f.object.class.to_s.tableize+"/"+association.to_s.singularize + "_fields"
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
     locals[:f] = builder
     locals[:disp] = disp
     render(:partial => partial, :locals => locals)
    end
    link_to name, '#', :onclick => "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", :class => "add-document-btn"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/upload_images_helper.rb
module UploadImagesHelper
end

app/views/categories/_form.html.haml
#wrapper
  #page-wrapper
    .container-fluid
      / Page Heading
      .row
        .col-lg-12
          %h1.page-header
            Upload New Images
          %ol.breadcrumb
            %li
              %i.fa.fa-dashboard
              %a{:href => "/upload_images"} Index
            %li.active
              %i.fa.fa-edit
              Forms
      / /.row
      .row
        .col-lg-6
          = form_for @category do |f|
            .form-group
              %label Category Name
              = f.text_field :name, class: "form-control"
              %br
              = f.submit "Save", class: "btn btn-primary"

app/views/categories/edit.html.haml
= render :partial => 'form'

app/views/categories/index.html.haml
#wrapper
  / Navigation
  #page-wrapper
    .container-fluid
      / Page Heading
      .row
        .col-lg-12
          %h1.page-header
            Category Listing
            %small  Category Overview
          / %ol.breadcrumb
          /   %li.active
          /     %i.fa.fa-dashboard
          /     Index
      / /.row
      .row
        .col-lg-12
          .alert.alert-info.alert-dismissable
            / %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
            %i.fa.fa-info-circle
            %strong 
            Try out
            %a.alert-link{:href => "/categories/new"} Add Category
      -  if flash[:notice].present?
        .row
          .col-lg-12
            .alert.alert-success.alert-dismissable
              %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
              = flash[:notice] if flash[:notice].present?
              = flash[:notice] = nil

      .row
        .col-lg-12
          = flash[:message] if flash[:message].present?
          = flash[:message] = nil
          .table-responsive
            %table.table.table-bordered.table-hover.table-striped
              %thead
                %tr
                  %th
                    Category Name
                  %th
                    Action
              %tbody
                - @categories.each do |category|
                  %tr
                    %td
                      = category.name
                    %td
                      = link_to "Edit", edit_category_path(:id => category.id), class: "btn btn-primary"
                      = link_to "Delete", category_path(:id => category.id), method: :delete, data: {confirm: "Are you sure?"},  class: "btn btn-danger"

app/views/categories/new.html.haml
= render :partial => 'form'

app/views/layouts/_side_menu.html.haml
.collapse.navbar-collapse.navbar-ex1-collapse
  %ul.nav.navbar-nav.side-nav
    %li{:class => params[:controller] == "products" ? "active" : ''}
      %a{:href => "/products"}
        %i.fa.fa-fw.fa-dashboard
        Product
    %li{:class => params[:controller] == "categories" ? "active" : ''}
      %a{:href => "/categories"}
        %i.fa.fa-fw.fa-bar-chart-o
        Category
    / %li
    /   %a{:href => "tables.html"}
    /     %i.fa.fa-fw.fa-table
    /     Tables
    / %li
    /   %a{:href => "forms.html"}
    /     %i.fa.fa-fw.fa-edit
    /     Forms
    / %li
    /   %a{:href => "bootstrap-elements.html"}
    /     %i.fa.fa-fw.fa-desktop
    /     Bootstrap Elements
    / %li
    /   %a{:href => "bootstrap-grid.html"}
    /     %i.fa.fa-fw.fa-wrench
    /     Bootstrap Grid
    / %li
    /   %a{"data-target" => "#demo", "data-toggle" => "collapse", :href => "javascript:;"}
    /     %i.fa.fa-fw.fa-arrows-v
    /     Dropdown
    /     %i.fa.fa-fw.fa-caret-down
    /   %ul#demo.collapse
    /     %li
    /       %a{:href => "#"} Dropdown Item
    /     %li
    /       %a{:href => "#"} Dropdown Item
    / %li
    /   %a{:href => "blank-page.html"}
    /     %i.fa.fa-fw.fa-file
    /     Blank Page
    / %li
    /   %a{:href => "index-rtl.html"}
    /     %i.fa.fa-fw.fa-dashboard
    /     RTL Dashboard
/ /.navbar-collapse

app/views/layouts/_top_menu.html.haml
#wrapper
  / Navigation
  %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/products"} Product
    / Top Menu Items
    %ul.nav.navbar-right.top-nav
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-envelope
          %b.caret
        %ul.dropdown-menu.message-dropdown
          %li.message-preview
            %a{:href => "#"}
              .media
                %span.pull-left
                  %img.media-object{:alt => "", :src => "http://placehold.it/50x50"}/
                .media-body
                  %h5.media-heading
                    %strong Nitin Rakesh
                  %p.small.text-muted
                    %i.fa.fa-clock-o
                    Yesterday at 4:32 PM
                  %p Lorem ipsum dolor sit amet, consectetur...
          %li.message-footer
            %a{:href => "#"} Read All New Messages
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-bell
          %b.caret
        %ul.dropdown-menu.alert-dropdown
          %li
            %a{:href => "#"}
              Alert Name
              %span.label.label-default Alert Badge
          %li.divider
          %li
            %a{:href => "#"} View All
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-user
          Nitin Rakesh
          %b.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#"}
              %i.fa.fa-fw.fa-user
              Profile
          %li
            %a{:href => "#"}
              %i.fa.fa-fw.fa-envelope
              Inbox
          %li
            %a{:href => "#"}
              %i.fa.fa-fw.fa-gear
              Settings
          %li.divider
          %li
            %a{:href => "#"}
              %i.fa.fa-fw.fa-power-off
              Log Out
    / Sidebar Menu Items - These collapse to the responsive navigation menu on small screens
    = render :partial => "layouts/side_menu"
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ckeditor</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <link href="http://font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
  <!-- <link href="http://plugins/morris.css" rel="stylesheet"> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render :partial => "layouts/top_menu"%>
<%= yield %>

</body>
</html>

app/views/products/_form.html.haml
#wrapper
  #page-wrapper
    .container-fluid
      .row
        .col-lg-12
          %h1.page-header
            Add Product
          %ol.breadcrumb
            %li
              %i.fa.fa-dashboard
              %a{:href => "/upload_images"} Index
            %li.active
              %i.fa.fa-edit
              Forms
      .row
        .col-lg-6
          = form_for @product do |f|
            .form-group
              %label Name
              = f.text_field :name, :class => "form-control"
            .form-group
              %label Category
              = f.fields_for :product_categories, :html => {:multipart => true}  do |builder|
                / - if params[:id].present?
                /   = select_tag 'role[]', options_for_select(Category.all.collect{|p| [p.name, p.id]}, "Nutritionist"), :prompt => "Select Speciality", :class => "form-control multiple"
                / - else
                = builder.select :category_id, options_for_select(Category.all.collect{|p| [p.name, p.id]}, :selected => f.object.categories.map(&:id)),{ :prompt => "Please select"}, :class => "form-control multiple" , :multiple =>"multiple"
                =# builder.select(:id, Category.all.collect{|p| [p.name, p.id]}, { :prompt => "Please select"}, :class => "form-control multiple", :multiple =>"multiple")
                = flash[:message] if flash[:message].present? 
                = flash[:message] = nil
            .form-group
              = f.submit "Save", class: "btn btn-primary"

:javascript
  $(".multiple").select2();

  

app/views/products/_upload_image_fields.html.haml
.hideDivimage
	.row
		.image-field
			= f.hidden_field :_destroy
			= f.link_to "X", "javascript:void(0);", :onclick => "remove_fields(this)"
			= f.file_field :image

app/views/products/_upload_image_lists.html.haml
.form-group.edit-image-fields.col-lg-12.tm5{:id => "temp_image_#{@temp_image.id}_div"}
  =image_tag(@temp_image.avatar.url,class: 'img-thumbnail')
  .input-group
    =hidden_field_tag 'upload_images[image_id][]',@temp_image.id
    =text_field_tag 'upload_images[description][]',nil, class: 'form-control well-inline-txt-input',:placeholder => 'Caption or Description'
  .edit-image-delete-order
    %button.delete_div.btn.btn-default.btn-sm{:type => 'button','data-id'=> "#temp_image_#{@temp_image.id}_div"}
      %span.delete_div.glyphicon.glyphicon-remove.btn_del_temp_image{'aria-hidden' => 'true'}
      Delete

app/views/products/edit.html.haml
= render :partial => 'form'

app/views/products/index.html.haml
#wrapper
  #page-wrapper
    .container-fluid
      .row
        .col-lg-12
          %h1.page-header
            Product Listing
            %small Image Overview
          %ol.breadcrumb
            %li.active
              %i.fa.fa-dashboard
              Index
      .row
        .col-lg-12
          .alert.alert-info.alert-dismissable
            / %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
            %i.fa.fa-info-circle
            %strong 
            Try out
            %a.alert-link{:href => "/products/new"} Add Product
      -  if flash[:notice].present?
        .row
          .col-lg-12
            .alert.alert-success.alert-dismissable
              %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
              = flash[:notice] if flash[:notice].present?
              = flash[:notice] = nil
      .row
        .col-lg-12
          .table-responsive
            %table.table.table-bordered.table-hover.table-striped
              %thead
                %tr
                  %th
                    Product Name
                  %th
                    Categories Name
                  %th
                    Action
              %tbody
                - @products.each do |product|
                  %tr
                    %td
                      = product.name
                    %td
                      = product.categories.map(&:name).join(',')
                    %td
                      = link_to "Edit", edit_product_path(:id => product.id), class: "btn btn-primary"
                      = link_to "Delete", product_path(:id => product.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/products/temp_image_update.js.erb
$('<%= @update_div_id %>').append("<%= escape_javascript( render partial: 'products/upload_image_lists') %>");
$('.media_file_field').val('');

app/views/upload_images/_form.html.haml
#wrapper
  #page-wrapper
    .container-fluid
      / Page Heading
      .row
        .col-lg-12
          %h1.page-header
            Upload New images
          %ol.breadcrumb
            %li
              %i.fa.fa-dashboard
              %a{:href => "/upload_images"} Index
            %li.active
              %i.fa.fa-edit
              Forms
      / /.row
      .row
        .col-lg-6
          = form_for @image , :html => {:multipart => true} do |f|
            .form-group
              %label File input
              = f.file_field :image, :multiple => true
              %br
              = f.submit "Upload", class: "btn.btn-primary"
              / %button.btn.btn-primary{:type => "submit"} Disabled Button
          / %h1 Form Validation
          / %form{:role => "form"}
          /   .form-group.has-success
          /     %label.control-label{:for => "inputSuccess"} Input with success
          /     %input#inputSuccess.form-control{:type => "text"}/
          /   .form-group.has-warning
          /     %label.control-label{:for => "inputWarning"} Input with warning
          /     %input#inputWarning.form-control{:type => "text"}/
          /   .form-group.has-error
          /     %label.control-label{:for => "inputError"} Input with error
          /     %input#inputError.form-control{:type => "text"}/
          / %h1 Input Groups
          / %form{:role => "form"}
          /   .form-group.input-group
          /     %span.input-group-addon @
          /     %input.form-control{:placeholder => "Username", :type => "text"}/
          /   .form-group.input-group
          /     %input.form-control{:type => "text"}/
          /     %span.input-group-addon .00
          /   .form-group.input-group
          /     %span.input-group-addon
          /       %i.fa.fa-eur
          /     %input.form-control{:placeholder => "Font Awesome Icon", :type => "text"}/
          /   .form-group.input-group
          /     %span.input-group-addon $
          /     %input.form-control{:type => "text"}/
          /     %span.input-group-addon .00
          /   .form-group.input-group
          /     %input.form-control{:type => "text"}/
          /     %span.input-group-btn
          /       %button.btn.btn-default{:type => "button"}
          /         %i.fa.fa-search
          / %p
          /   For complete documentation, please visit
          /   = succeed "." do
          /     %a{:href => "http://getbootstrap.com/css/#forms"} Bootstrap's Form Documentation
      / /.row
    / /.container-fluid
  / /#page-wrapper
/ /#wrapper

app/views/upload_images/index.html.haml
#wrapper
  / Navigation
  #page-wrapper
    .container-fluid
      / Page Heading
      .row
        .col-lg-12
          %h1.page-header
            Index
            %small Image Overview
          %ol.breadcrumb
            %li.active
              %i.fa.fa-dashboard
              Index
      / /.row
      .row
        .col-lg-12
          .alert.alert-info.alert-dismissable
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
            %i.fa.fa-info-circle
            %strong 
            Try out
            %a.alert-link{:href => "/upload_images/new"} Upload New Image
      / /.row
      .row
        - @images.each do |image|
          .col-lg-3.col-md-6
            = image_tag (image.image.url(:small))
      / /.row
      / /.row